quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/orderdb
quarkus.hibernate-orm.database.generation=update
quarkus.rest-client.exchange-api.url=https://open.er-api.com
quarkus.rest-client.exchange-api.scope=jakarta.inject.Singleton
mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=order-events
mp.messaging.outgoing.order-created.value.serializer=io.quarkus.kafka
mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=order-events
mp.messaging.outgoing.order-created.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.incoming.order-events.connector=smallrye-kafka
mp.messaging.incoming.order-events.topic=order-events
mp.messaging.incoming.order-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Docker Compose Kafka
quarkus.kafka.devservices.enabled=false
mp.messaging.outgoing.order-created.bootstrap.servers=kafka:9092
mp.messaging.incoming.order-events.bootstrap.servers=kafka:9092
